### ISSUE TITLE
Liquid Exception 'faker' tag was never closed

### ISSUE THREAD

**Issue by VacantFuture** [anomaly/jekyll-faker#2]
{% faker lorem sentences=8 %}
  <p>{{ faker.val }}</p>
{% endfaker %}

error - " Liquid Exception: Liquid syntax error (line 3): 'faker' tag was never closed in /Users/jamesnobles/Documents/dev projects/NewsSite/_posts/2018-12-30-what-the-hemp.markdown"

MacOS Mojave
Jekyll 3.8.5
ruby 2.3.5

Trace-
bundler: failed to load command: jekyll (/Users/jamesnobles/.rbenv/versions/2.3.5/bin/jekyll)
Liquid::SyntaxError: Liquid syntax error (line 3): 'faker' tag was never closed
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/liquid-4.0.1/lib/liquid/block.rb:63:in `block in parse_body'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/liquid-4.0.1/lib/liquid/block_body.rb:52:in `parse'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/liquid-4.0.1/lib/liquid/block.rb:58:in `parse_body'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/liquid-4.0.1/lib/liquid/block.rb:12:in `parse'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/liquid-4.0.1/lib/liquid/tag.rb:10:in `parse'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/liquid-4.0.1/lib/liquid/block_body.rb:34:in `parse'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/liquid-4.0.1/lib/liquid/document.rb:10:in `parse'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/liquid-4.0.1/lib/liquid/document.rb:5:in `parse'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/liquid-4.0.1/lib/liquid/template.rb:132:in `parse'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/liquid-4.0.1/lib/liquid/template.rb:116:in `parse'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/liquid_renderer/file.rb:13:in `block in parse'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/liquid_renderer/file.rb:12:in `parse'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:121:in `render_liquid'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:79:in `render_document'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:62:in `run'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:479:in `render_regenerated'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:464:in `block (2 levels) in render_docs'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:463:in `each'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:463:in `block in render_docs'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:462:in `each_value'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:462:in `render_docs'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:191:in `render'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:71:in `process'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/command.rb:28:in `process_site'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:65:in `build'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:36:in `process'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /Users/jamesnobles/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/jekyll-3.8.5/exe/jekyll:15:in `<top (required)>'
  /Users/jamesnobles/.rbenv/versions/2.3.5/bin/jekyll:22:in `load'
  /Users/jamesnobles/.rbenv/versions/2.3.5/bin/jekyll:22:in `<top (required)>'

**Comment by VacantFuture** [comment]
Sorry, figured it out. Was an issue with space/tab Sublime, not this gem.
